version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_drzavnamatura
      MYSQL_DATABASE: drzavnamatura
      MYSQL_USER: drzavnamatura
      MYSQL_PASSWORD: drzavnamatura
    ports:
      - 1234:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  db_data: {}